name: Databricks Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Load Python dependencies
        run: pip install pytest requests setuptools wheel

      - name: Get Changes
        run: |
          mkdir -p build_output
          cp ${{ github.workspace }}/*.* build_output/

      - name: Archive Files
        run: |
          mkdir -p artifact_staging
          cd build_output
          zip -r ../artifact_staging/${{ github.run_id }}.zip .

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DatabricksBuild
          path: artifact_staging/${{ github.run_id }}.zip